engines:
  structure:
    enabled: false
  duplication:
    enabled: false
  sonar-java:
    enabled: true
    channel: beta
    config:
      sonar.sourceEncoding: us-ascii
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**/*.jpeg"
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
